-- Create jobs table for Job Service
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description LONGTEXT NOT NULL,
    company VARCHAR(200) NOT NULL,
    location VARCHAR(100) NOT NULL,
    job_type VARCHAR(50),
    experience_level VARCHAR(50),
    status VARCHAR(50) DEFAULT 'ACTIVE',
    salary_min DECIMAL(12, 2),
    salary_max DECIMAL(12, 2),
    salary_currency VARCHAR(10) DEFAULT 'USD',
    requirements LONGTEXT,
    responsibilities LONGTEXT,
    category VARCHAR(100),
    skills TEXT,
    recruiter_id BIGINT NOT NULL,
    application_deadline DATETIME,
    is_remote BOOLEAN DEFAULT FALSE,
    views_count INT DEFAULT 0,
    applications_count INT DEFAULT 0,
    created_at DATETIME,
    updated_at DATETIME,
    INDEX idx_recruiter_id (recruiter_id),
    INDEX idx_status (status),
    INDEX idx_location (location),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
