server:
  port: 8086
  address: 0.0.0.0

spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}"
  application:
    name: admin-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.jobportal: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
